spring:
  datasource:
    username: root
    password: 12345
    url: jdbc:mysql://localhost:3306/ssm
    driver-class-name: com.mysql.jdbc.Driver
    schema:
      - classpath:employee.sql
      - classpath:department.sql